In [ ]:
# Bai 1-1: do dai cua vector
import numpy as np

def compute_vector_length(vector):
  return np.sqrt(np.sum(vector**2))

def compute_vector_length1(vector):
  len_of_vector = np.linalg.norm(vector)
  return len_of_vector

# Test
vector = np.array([-2, 4, 9, 21])
result = compute_vector_length1(vector)
print(round(result,2))

23.28


In [16]:
# Bai 1-2: Phep tich vo huong
import numpy as np

# Theo cong thuc
def compute_dot_product(vector1, vector2):
  return np.sum(vector1 * vector2)

# Test: Vector vs Vector
v1 = np.array([0, 1, -1, 2])
v2 = np.array([2, 5, 1, 0])
result = compute_dot_product(v1, v2)
print('Vector vs Vector: ',round(result,2))

# Su dung thu vien numpy
def compute_dot_product1(vector1, vector2):
  result = np.dot(vector1, vector2)
  return result

# Test: Matrix vs Vector
x = np.array([[1,2],[3,4]])
k = np.array([1,2])
print('Matrix vs Vector:', compute_dot_product1(x,k))

# Test: others
x = np.array([[-1,2],[3,-4]])
k = np.array([1,2])
print('result 2:',x.dot(k))
print('result 3:', x@k)

Vector vs Vector:  4
Matrix vs Vector: [ 5 11]
result 2: [ 3 -5]
result 3: [ 3 -5]


In [17]:
# Bai 1-3: Matrix vs Vector
import numpy as np

def matrix_multi_vector(matrix, vector):
  result = np.dot(matrix,vector)
  return result

# Test: Matrix vs Vector
x = np.array([[-1,1,1],[0,-4,9]])
k = np.array([0,2,1])
result = matrix_multi_vector(x,k)
print(result)

[3 1]


In [ ]:
# Bai 1-4: Matrix vs Matrix
import numpy as np

def matrix_multi_matrix(matrix1, matrix2):
  result = np.dot(matrix1,matrix2)
  return result

# Test: Matrix vs Matrix
m1 = np.array([[0,1,2],[2,-3,1]])
m2 = np.array([[1,-3],[6,1],[0,-1]])
result = matrix_multi_matrix(m1,m2)
print(result)

[[  6  -1]
 [-16 -10]]


In [ ]:
# Bai 1-5: Matrix Inverse
import numpy as np

def inverse_matrix(matrix):
  result = np.linalg.inv(matrix)
  return result

# Test: Matrix Inverse
m1 = np.array([[-2, 6], [8, -4]])
result = inverse_matrix(m1)
print(result)

[[0.1  0.15]
 [0.2  0.05]]


In [ ]:
# Bai 2-1: Eigenvector and eigenvalue
import numpy as np

def compute_eigenvalues_eigenvectors(matrix):
  eigenvalues, eigenvectors = np.linalg.eig(matrix)
  return eigenvalues,eigenvectors

# Test:
matrix = np.array([[0.9, 0.2], [0.1, 0.8]])
eigenvalues, eigenvectors = compute_eigenvalues_eigenvectors(matrix)
print(eigenvectors)

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [ ]:
import numpy as np
from numpy import dot
from numpy.linalg import norm

def compute_vector_length(vector):
  len_of_vector = np.linalg.norm(vector)
  return len_of_vector

def compute_dot_product(vector1, vector2):
  result = np.dot(vector1, vector2)
  return result

def compute_cosine(v1, v2):
  cos_sim = compute_dot_product(v1,v2) / (compute_vector_length(v1)*compute_vector_length(v2))
  return cos_sim

# Test: Vector vs Vector
x = np.array([1, 2, 3, 4])
y = np.array([1, 0, 3, 0])
result = compute_cosine(x,y)
print(round(result, 3))

0.577


In [20]:
# Trac nghiem - cau 7
m1 = np.eye(3)
m2 = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
result = m1@m2
print(result)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [22]:
# Trac nghiem - cau 8
m1 = np.eye(2)
m1 = np.reshape(m1,(-1,4))[0]
m2 = np.array([[1, 1, 1,1], [2, 2, 2,2], [3, 3, 3,3], [4, 4, 4,4]])
result = m1@m2
print(result)

[5. 5. 5. 5.]


In [23]:
# Trac nghiem - cau 9
m1 = np.array([[1,2],[3,4]])
m1 = np.reshape(m1,(-1,4),"F")[0]
m2 = np.array([[1, 1, 1,1], [2, 2, 2,2], [3, 3, 3,3], [4, 4, 4,4]])
result = m1@m2
print(result)

[29 29 29 29]
